Upload an image to a Book
CMPUT301F20T15/BookwormAdventuresDeluxe2 pull request #45
Opened 2020-10-31 23:21 UTC by KateVlaar

Now when adding a new book or editing an old one, by clicking 'Upload Photo' user may select a photo from their gallery to upload. Each book can only map to one image at an old time so if you attempt to upload an image when one already exists, the old one will be deleted. Photos are stored in Fire Storage and their download URL's are stored within the book and updated with FireStore accordingly.

2020-10-31 23:22 UTC, KateVlaar commented
![image](https://user-images.githubusercontent.com/44733046/97791939-8def0780-1b9d-11eb-9cb8-05de394a6304.png)
![image](https://user-images.githubusercontent.com/44733046/97791947-96474280-1b9d-11eb-9bea-533d6cc11164.png)

2020-11-01 01:22 UTC, naviza approved these changes
I tested it and it looks great! Although regarding what Paul said about US 08.01.01, are we only letting the users upload pictures for now? If yes, we should add the camera option as a potential feature in the future.

2020-11-01 01:22 UTC, naviza commented on app/src/main/java/com/example/bookwormadventuresdeluxe2/AddOrEditBooksActivity.java
> +    public void uploadPhoto(View view)
rude.

2020-11-01 02:01 UTC, IsaakC reviewed
When I scroll through the My Requests and Borrow lists (with all the books) the images seem to apply to the wrong books and also swap during scrolling

2020-11-01 05:13 UTC, huddy987 commented
> When I scroll through the My Requests and Borrow lists (with all the books) the images seem to apply to the wrong books and also swap during scrolling

This might be an issue with the view in my Reuqests and Borrows and not an issue with this commit

2020-11-01 05:23 UTC, huddy987 requested changes
There's a bug with this PR:

1. Create a book without a picture
2. Click edit on the book and add a picture
3. The picture does not show up

This is the perfect PR to add 2 interface tests:
1. Create a new book with a picture
2. Create a new book, then edit it and add a picture

That way if this breaks in the future we will know

2020-11-01 17:47 UTC, naviza commented
> There's a bug with this PR:
> 
> 1. Create a book without a picture
> 2. Click edit on the book and add a picture
> 3. The picture does not show up
> 
> This is the perfect PR to add 2 interface tests:
> 
> 1. Create a new book with a picture
> 2. Create a new book, then edit it and add a picture
> 
> That way if this breaks in the future we will know

Maybe Add this as a separate JIRA ticket? I can work on top of this branch and implement that.

2020-11-01 18:20 UTC, KateVlaar commented
> > There's a bug with this PR:
> > 
> > 1. Create a book without a picture
> > 2. Click edit on the book and add a picture
> > 3. The picture does not show up
> > 
> > This is the perfect PR to add 2 interface tests:
> > 
> > 1. Create a new book with a picture
> > 2. Create a new book, then edit it and add a picture
> > 
> > That way if this breaks in the future we will know
> 
> Maybe Add this as a separate JIRA ticket? I can work on top of this branch and implement that.

I actually can't seem to reproduce it but I am more than happy to make the tests. However I did find a new bug which I am working on: 1. Add a new book without picture 2. Book appears to have a picture in MyBooks

2020-11-02 00:15 UTC, KateVlaar commented
Fixed bug where wrong pictures show up with books. Unit tests to come in a future PR

2020-11-02 06:08 UTC, IsaakC approved these changes

2020-11-02 16:05 UTC, merged