set username when request -> accept
CMPUT301F20T15/BookwormAdventuresDeluxe2 pull request #98
Opened 2020-11-28 18:33 UTC by IsaakC

previously it wasnt set until so username was blank during transition from requested -> accepted
also got rid of some unused xml code
![image](https://user-images.githubusercontent.com/69653695/100523402-7e97b580-316d-11eb-80a2-fbc4ca934e72.png)

2020-11-28 18:50 UTC, KateVlaar approved these changes

2020-11-28 19:47 UTC, huddy987 requested changes

2020-11-28 19:47 UTC, huddy987 commented on app/src/main/java/com/example/bookwormadventuresdeluxe2/RequestDetailViewFragment.java
> +                    System.out.println("yes");
Please remove the print

2020-11-28 20:18 UTC, IsaakC commented on app/src/main/java/com/example/bookwormadventuresdeluxe2/RequestDetailViewFragment.java
> +                    System.out.println("yes");
whoops good catch

2020-11-29 00:58 UTC, JawadHossain approved these changes

2020-11-29 01:34 UTC, huddy987 requested changes

2020-11-29 01:34 UTC, huddy987 commented on .gitignore
> +app/src/main/java/com/example/bookwormadventuresdeluxe2/NotificationUtility/CloudMessagingServerKeyConstant.java
This should not be added

2020-11-29 01:43 UTC, huddy987 requested changes

2020-11-29 01:43 UTC, huddy987 commented on .gitignore
> -app/src/main/java/com/example/bookwormadventuresdeluxe2/Utilities/NotificationUtility/CloudMessagingServerKeyConstant.java
Leave this one in the gitignore as it is the new path, remove the one below. Remove the other file from github pls

2020-11-29 01:56 UTC, huddy987 approved these changes

2020-11-29 02:03 UTC, merged