Cancel request from borrower side & hide delete button on borrowed book
CMPUT301F20T15/BookwormAdventuresDeluxe2 pull request #99
Opened 2020-11-28 20:28 UTC by n00b4ever

*Add cancel button for borrower side
    (if requester.size after delete == 0, set to Available)
    (if requesters.size > 0 after delete, keep Requested)

*MyBooksDetailViewFragment also updates when book changes
    Tried to make snapshot listener in superclass for all detailView but failed.

2020-11-28 23:41 UTC, IsaakC requested changes
cancel request seems to work fine.
Hiding the delete button is not implemented correctly. Currently it only hides the option when the books real status == Borrowed, but allows deletion when the book is bPending and rPending. 

Technically with our implementation I think we could get away with deletion at any time in the process, but if we choose to hide the delete button when the book is Borrowed then it should be hidden during bPending, Borrowed, and rPending.

2020-11-29 01:44 UTC, KateVlaar requested changes
Can you remove the allCaps="false" option on the cancel request button. Looks good other than what Isaak pointed out

2020-11-29 02:11 UTC, IsaakC commented
![image](https://user-images.githubusercontent.com/69653695/100530296-7cede200-31ad-11eb-8a28-f8d9fb5e1c85.png)

2020-11-29 02:14 UTC, KateVlaar approved these changes

2020-11-29 02:23 UTC, IsaakC approved these changes

2020-11-29 02:32 UTC, merged